name: "release"

on:
  push:
    # タグがつけられたら駆動
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
#        os: [ macos-latest, ubuntu-latest, windows-latest ] # macOS、Ubuntu、Windowsでビルド作業を行う
        os: [ ubuntu-latest ]

    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: setup snapcraft (ubuntu only)
        run: |
          sudo apt install snapd
          sudo snap install snapcraft --classic

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GH_TOKEN }}

          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
