name: "release"

on:
  push:
    # タグがつけられたら駆動
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
#        os: [ macos-latest, ubuntu-latest, windows-latest ] # macOS、Ubuntu、Windowsでビルド作業を行う
        os: [windows-latest, macos-latest]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: npm install
        run: |
          npm install

      - name: build
        run: |
          npm run dist
