name: "release"

on:
  push:
    # タグがつけられたら駆動
    tags:
      - 'v*'

env:
  GH_TOKEN: ${{secrets.GH_TOKEN}}

jobs:
  release:
#    runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest

    #    strategy:
#      matrix:
#        os: [ macos-latest, ubuntu-latest, windows-latest ] # macOS、Ubuntu、Windowsでビルド作業を行う
#        os: [ubuntu-latest]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: install software (ubuntu only)
#        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install snapd -y
          sudo snap install snapcraft --classic

      - name: npm install
        run: |
          npm install

      - name: build
        run: |
          npm run build
          npm run dist
